# Application Info
info:
  application:
    name: api-gateway
    description: API Gateway
    author: Shubham Shinde
    version: '@project.version@'

# Server Config
server:
  port: 8080

# Spring Security Config
logging:
  level.*: trace

# API GateWay Config
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
  cloud:
    gateway:
      routes:
        - id: authorization_server
          uri: http://localhost:9000
          predicates:
            - Path=/users/**
          filters:
            - PrefixPath=/api/V1

# Actuator Endpoints
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: health, info
  info:
    env:
      enabled: true