# Application Info
info:
  application:
    name: api-gateway
    description: API Gateway
    author: Shubham Shinde
    version: '@project.version@'

# Server Config
server:
  port: 8080

# Spring Security Config
logging:
  level.*: trace

spring:
  cloud:
    gateway:
      routes:
        - id: authorization_server
          uri: http://localhost:9000/login
          predicates:
            - Path=/auth